
services:
  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Порт 80 контейнера -> порт 8080 на хосте
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Порт 5000 контейнера -> порт 3000 на хосте